on:
  push:
  pull_request:

name: ğŸ—ï¸ Build Windows

# Linux builds are tested in `test.yml`, we don't build them separately here.
# The Windows builds are "special" in this regard because they don't properly run in GitHub Workflows.

jobs:
  build-prebuilt-release:
    runs-on: windows-latest

    steps:
      - name: ğŸ“¥ Checkout
        uses: actions/checkout@v3

      - name: ğŸ”¨ Build
        run: |
          cmake -B build -Dsaucer_backend=WebView2 -Dsaucer_package_all=ON
          cmake --build build --config RelWithDebInfo
          cmake --install build --prefix 'saucer-artifact' --config RelWithDebInfo

      - name: ğŸ“¦ Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Pre-Built (Release)
          path: saucer-artifact

  build-prebuilt-debug:
    runs-on: windows-latest

    steps:
      - name: ğŸ“¥ Checkout
        uses: actions/checkout@v3

      - name: ğŸ”¨ Build
        run: |
          cmake -B build -Dsaucer_backend=WebView2 -Dsaucer_package_all=ON
          cmake --build build --config Debug
          cmake --install build --prefix 'saucer-artifact' --config Debug

      - name: ğŸ“¦ Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Pre-Built (Debug)
          path: saucer-artifact
